// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"outergeekhub.com/codsworthpost/domain/usecases"
	"outergeekhub.com/codsworthpost/infrastructure/driven-adapters/firebaseDb-provider"
	"outergeekhub.com/codsworthpost/infrastructure/entry-points/api_rest"
)

// Injectors from setup.go:

func Setup() *Components {
	postService := firebasedbprovider.NewPostService()
	postPublisher := usecases.NewPostPublisher(postService)
	publishPostPostController := apirest.NewPublishPostPostController(postPublisher)
	components := initComponents(publishPostPostController)
	return components
}
