// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"outergeekhub.com/codsworthpost/domain/usecases"
	"outergeekhub.com/codsworthpost/infrastructure/driven-adapters/post-provider"
	"outergeekhub.com/codsworthpost/infrastructure/entry-points/web"
)

// Injectors from setup.go:

func Setup() *Components {
	postService := post_Provider.NewPostService()
	postPublisher := usecases.NewPostPublisher(postService)
	homeController := web.NewHomeController(postPublisher)
	components := initComponents(postService, postPublisher, homeController)
	return components
}
